global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'opentelemetry-collector'
    scrape_interval: 1s
    static_configs:
      - targets: ['opentelemetry-collector:8889'] # Ensure this port is exposed for Prometheus metrics in the OpenTelemetry Collector
  - job_name: 'cadvisor'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor:8080']
  # Add scrape configurations for other services if they expose metrics
